version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    volumes:
      - ./fuel:/var/www/fuel
    depends_on:
      - db
    # command: tail -F anything # 初回のみコメント外す。

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
  